version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=web_dev1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hayneslorena2912
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8001"
    depends_on:
      - db
