# Generated by Django 2.2 on 2020-05-04 18:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20200504_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for URL config.', max_length=31, populate_from=['name'], unique=True),
        ),
    ]
