# Generated by Django 2.2 on 2020-05-04 18:26

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_auto_20200504_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=31, populate_from=['title']),
        ),
    ]
