# Generated by Django 2.2 on 2020-05-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_newslink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Newslink',
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
